/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacommunicationarduino;

import com.embeddedunveiled.serial.SerialComDataEvent;

/**
 * Class that generate the jframe
 * @author romain
 */
public class InterfaceCommunication extends javax.swing.JFrame
{
    /**
     * model used to manage serial communication
     */
    private JavaCommunicationModele model;
    /**
     * 
     */
    public DataListener dataListener;
    
    /**
     * Creates new form InterfaceCommunication
     */
    public InterfaceCommunication(JavaCommunicationModele com) 
    {
        initComponents();
        this.model = com;
        this.dataListener = new DataListener()
        {
            @Override
            public void onNewSerialDataAvailable(SerialComDataEvent data)
            {
                parseData(new String(data.getDataBytes()));
            }
        };
        setPortList();
    }
    
    /**
     * set the port list in combo box liste of port
     */
    public void setPortList()
    {
        for(String port: this.model.getPortList())
        {
            this.jCB_ListPort.addItem(port);
        }
    }
    
    /**
     * Récupere les valeur reçus via le ports série et les affiche dans leur textfield respectif
     * @param data String received from serial
     */
    public void parseData(String data)
    {
        String[] parsedLine = data.split("\n");
        if(parsedLine.length > 0)
        {
            for(String parse: parsedLine)
            {
               String[] parsed = parse.split(" ");
               if(parsed.length > 0)
               {
                    switch(parsed[0])
                    {
                        case "IMU" :
                            try
                            {
                                if(parsed.length > 3)
                                {
                                    if(parsed[1].split(":").length == 2)
                                        this.jTxtRoll.setText(parsed[1].split(":")[1]);
                                    if(parsed[2].split(":").length == 2)
                                        this.jTxtPitch.setText(parsed[2].split(":")[1]);
                                    if(parsed[3].split(":").length == 2)
                                        this.jTxtYaw.setText(parsed[3].split(":")[1]);
                                }
                            }
                            catch(Exception e)
                            {
                                System.out.println("parse => "+parse);
                                System.out.println("parse => "+parsed);
                                e.printStackTrace();
                            }
                         break;
                        case "GYRO" :
                            try
                            {
                                if(parsed.length > 3)
                                {
                                    if(parsed[1].split(":").length == 2)
                                        this.jTxtX.setText(parsed[1].split(":")[1]);
                                    if(parsed[2].split(":").length == 2)
                                        this.jTxtY.setText(parsed[2].split(":")[1]);
                                    if(parsed[3].split(":").length == 2)
                                        this.jTxtZ.setText(parsed[3].split(":")[1]);
                                }
                            }
                            catch(Exception e)
                            {
                                System.out.println("parse => "+parse);
                                System.out.println("parse => "+parsed);
                                e.printStackTrace();
                            }
                         break;   
                        default:
                            break;
                    }
               }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlControle = new javax.swing.JPanel();
        jCB_ListPort = new javax.swing.JComboBox();
        lblPortComm = new javax.swing.JLabel();
        jTBConnect = new javax.swing.JToggleButton();
        jBtnRefresh = new javax.swing.JButton();
        jCbtn_BaudRate = new javax.swing.JComboBox();
        jLblBaudeRate = new javax.swing.JLabel();
        jPnlAccelero = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLblRoll = new javax.swing.JLabel();
        jLblPitch = new javax.swing.JLabel();
        jLblYaw = new javax.swing.JLabel();
        jLblIMU = new javax.swing.JLabel();
        jLblGyro = new javax.swing.JLabel();
        jLblX = new javax.swing.JLabel();
        jLblY = new javax.swing.JLabel();
        jLblZ = new javax.swing.JLabel();
        jTxtRoll = new javax.swing.JTextField();
        jTxtPitch = new javax.swing.JTextField();
        jTxtYaw = new javax.swing.JTextField();
        jTxtX = new javax.swing.JTextField();
        jTxtY = new javax.swing.JTextField();
        jTxtZ = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        JSclPnlTxtArea = new javax.swing.JScrollPane();
        jTxtAreaMsg = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jCB_ListPort.setMinimumSize(new java.awt.Dimension(90, 20));
        jCB_ListPort.setPreferredSize(new java.awt.Dimension(90, 20));

        lblPortComm.setLabelFor(jCB_ListPort);
        lblPortComm.setText("List Serial Port");

        jTBConnect.setLabel("Connection");
        jTBConnect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jTBConnectItemStateChanged(evt);
            }
        });

        jBtnRefresh.setText("Rafraichir la Liste");
        jBtnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnRefreshMouseClicked(evt);
            }
        });

        jCbtn_BaudRate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "300", "600", "1200", "2400", "4800", "9600", "14400", "19200", "28800", "38400", "57600", "115200" }));
        jCbtn_BaudRate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbtn_BaudRateItemStateChanged(evt);
            }
        });

        jLblBaudeRate.setText("Baud Rate");

        javax.swing.GroupLayout jPnlControleLayout = new javax.swing.GroupLayout(jPnlControle);
        jPnlControle.setLayout(jPnlControleLayout);
        jPnlControleLayout.setHorizontalGroup(
            jPnlControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlControleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPortComm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCB_ListPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblBaudeRate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbtn_BaudRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTBConnect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlControleLayout.setVerticalGroup(
            jPnlControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlControleLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPnlControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_ListPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPortComm)
                    .addComponent(jTBConnect)
                    .addComponent(jBtnRefresh)
                    .addComponent(jCbtn_BaudRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblBaudeRate))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Accelerometre");

        jLblRoll.setText("Roll");

        jLblPitch.setText("Pitch");
        jLblPitch.setToolTipText("");

        jLblYaw.setText("Yaw");

        jLblIMU.setText("IMU");

        jLblGyro.setText("Gyro");

        jLblX.setText("X");

        jLblY.setText("Y");

        jLblZ.setText("Z");

        jTxtRoll.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtRoll.setText("0");

        jTxtPitch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtPitch.setText("0");

        jTxtYaw.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtYaw.setText("0");

        jTxtX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtX.setText("0");

        jTxtY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtY.setText("0");

        jTxtZ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtZ.setText("0");

        javax.swing.GroupLayout jPnlAcceleroLayout = new javax.swing.GroupLayout(jPnlAccelero);
        jPnlAccelero.setLayout(jPnlAcceleroLayout);
        jPnlAcceleroLayout.setHorizontalGroup(
            jPnlAcceleroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAcceleroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlAcceleroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPnlAcceleroLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPnlAcceleroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblIMU)
                            .addComponent(jLblGyro)
                            .addGroup(jPnlAcceleroLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPnlAcceleroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPnlAcceleroLayout.createSequentialGroup()
                                        .addComponent(jLblZ)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTxtZ))
                                    .addGroup(jPnlAcceleroLayout.createSequentialGroup()
                                        .addGroup(jPnlAcceleroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblPitch)
                                            .addComponent(jLblYaw)
                                            .addComponent(jLblRoll))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPnlAcceleroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtRoll, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(jTxtYaw)
                                            .addComponent(jTxtPitch)))
                                    .addGroup(jPnlAcceleroLayout.createSequentialGroup()
                                        .addComponent(jLblX)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTxtX))
                                    .addGroup(jPnlAcceleroLayout.createSequentialGroup()
                                        .addComponent(jLblY)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTxtY)))))))
                .addContainerGap())
        );
        jPnlAcceleroLayout.setVerticalGroup(
            jPnlAcceleroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAcceleroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblIMU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlAcceleroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblRoll)
                    .addComponent(jTxtRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlAcceleroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPitch)
                    .addComponent(jTxtPitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlAcceleroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblYaw)
                    .addComponent(jTxtYaw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblGyro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlAcceleroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblX)
                    .addComponent(jTxtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlAcceleroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblY)
                    .addComponent(jTxtY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlAcceleroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblZ)
                    .addComponent(jTxtZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(300, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTxtAreaMsg.setColumns(20);
        jTxtAreaMsg.setRows(5);
        JSclPnlTxtArea.setViewportView(jTxtAreaMsg);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JSclPnlTxtArea, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JSclPnlTxtArea)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlAccelero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnlControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPnlAccelero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * appelle la fonction pour connecter le port serie selectionné ou le déconnecter selon l'état du bouton
     * @param evt 
     */
    private void jTBConnectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jTBConnectItemStateChanged
        if(this.jTBConnect.isSelected())
        {
            this.jTxtAreaMsg.append(this.model.openConnection( this.jCB_ListPort.getSelectedIndex()) + "\n");
            if(this.model.isConnected())
            {
                this.jTBConnect.setText("Deconnection");
            }
        }
        else
        {
            this.jTxtAreaMsg.append(this.model.closeConnection()+"\n");
            if(!this.model.isConnected())
            {
                this.jTBConnect.setText("Connection");
            }
        }
    }//GEN-LAST:event_jTBConnectItemStateChanged

    /**
     * appelle la fonction pour rafraichier la liste des port serie disponible
     * @param evt 
     */
    private void jBtnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRefreshMouseClicked
        this.jTxtAreaMsg.append(this.model.refreshPortList()+"\n");
        this.jCB_ListPort.removeAllItems();
        this.setPortList();
    }//GEN-LAST:event_jBtnRefreshMouseClicked

    /**
     * appelle la fonction pour changer le baudrate du port série lorsque l'on en a selectionné un autre
     * @param evt 
     */
    private void jCbtn_BaudRateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbtn_BaudRateItemStateChanged
        this.jTxtAreaMsg.append(this.model.setBaudRate(Integer.decode(this.jCbtn_BaudRate.getSelectedItem().toString()))+"\n");
    }//GEN-LAST:event_jCbtn_BaudRateItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCommunication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCommunication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCommunication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCommunication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCommunication().setVisible(true);
            }
        });
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JSclPnlTxtArea;
    private javax.swing.JButton jBtnRefresh;
    private javax.swing.JComboBox jCB_ListPort;
    private javax.swing.JComboBox jCbtn_BaudRate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblBaudeRate;
    private javax.swing.JLabel jLblGyro;
    private javax.swing.JLabel jLblIMU;
    private javax.swing.JLabel jLblPitch;
    private javax.swing.JLabel jLblRoll;
    private javax.swing.JLabel jLblX;
    private javax.swing.JLabel jLblY;
    private javax.swing.JLabel jLblYaw;
    private javax.swing.JLabel jLblZ;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPnlAccelero;
    private javax.swing.JPanel jPnlControle;
    private javax.swing.JToggleButton jTBConnect;
    private javax.swing.JTextArea jTxtAreaMsg;
    private javax.swing.JTextField jTxtPitch;
    private javax.swing.JTextField jTxtRoll;
    private javax.swing.JTextField jTxtX;
    private javax.swing.JTextField jTxtY;
    private javax.swing.JTextField jTxtYaw;
    private javax.swing.JTextField jTxtZ;
    private javax.swing.JLabel lblPortComm;
    // End of variables declaration//GEN-END:variables
}
